CREATE DATABASE IF NOT EXISTS PRACTICA3;

USE PRACTICA3;

DROP TABLE IF EXISTS LOCATION_TEMP;
DROP TABLE IF EXISTS GEONAME_TEMP;
DROP TABLE IF EXISTS LEVEL_1A_TEMP;
DROP TABLE IF EXISTS PROJECT_TEMP;
DROP TABLE IF EXISTS COUNTRY_CODE_TEMP;
DROP TABLE IF EXISTS TRANSACTION_TEMP;

DROP TABLE IF EXISTS `TRANSACTION`;
DROP TABLE IF EXISTS CURRENCY;
DROP TABLE IF EXISTS LEVEL_1A;
DROP TABLE IF EXISTS PROJECT;
DROP TABLE IF EXISTS TYPE_STATUS;
DROP TABLE IF EXISTS COUNTRY_CODE;
DROP TABLE IF EXISTS GEONAME;
DROP TABLE IF EXISTS `LOCATION`;
